name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: 'Install dependencies'
        run: pnpm install --prefer-frozen-lockfile

      - name: Lint
        run: pnpm run lint
      
      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

